/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnePagerRouteImport } from './routes/one-pager'
import { Route as IndexRouteImport } from './routes/index'

const OnePagerRoute = OnePagerRouteImport.update({
  id: '/one-pager',
  path: '/one-pager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/one-pager': typeof OnePagerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/one-pager': typeof OnePagerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/one-pager': typeof OnePagerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/one-pager'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/one-pager'
  id: '__root__' | '/' | '/one-pager'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnePagerRoute: typeof OnePagerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/one-pager': {
      id: '/one-pager'
      path: '/one-pager'
      fullPath: '/one-pager'
      preLoaderRoute: typeof OnePagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnePagerRoute: OnePagerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
